### ISSUE TITLE
Cannot open camera on port 1

### ISSUE THREAD

**Issue by CarterFendley** [robotpy/robotpy-cscore#15]
I have two usb cameras plugged in and they are both in `/dev` but when I try to open a camera on port one it doesnt not work
![screen shot 2017-02-09 at 3 45 13 pm](https://cloud.githubusercontent.com/assets/8919742/22802799/40b0d7a2-eee0-11e6-9567-0cfe3e87efe5.png)

**Comment by virtuald** [comment]
You're passing a string to UsbCamera, it requires an integer. I'll see if there's a way to make that error happen.
