### ISSUE TITLE
Sync code with 2018 updates

### ISSUE THREAD

**Issue by virtuald** [robotpy/robotpy-cscore#20]

**Comment by auscompgeek** [comment]
I think this is done.

**Comment by auscompgeek** [comment]
Then again, should double-check that CameraServer is up-to-date.

**Comment by virtuald** [comment]
Yeah, that piece needs to be done still.

**Comment by auscompgeek** [comment]
WIP for CameraServer at https://github.com/auscompgeek/robotpy-cscore/tree/cameraserver-2018 - feel free to continue working off this.

**Comment by virtuald** [comment]
I've added git-source-track stuff, so it should be easier to track in the future.

**Comment by auscompgeek** [comment]
I'm just going to call this done for today.
