### ISSUE TITLE
Fix compilation on Jetson (OpenCV 2)

### ISSUE THREAD

**Issue by virtuald** [robotpy/robotpy-cscore#22]
I'm pretty sure OpenCV on the Jetson is OpenCV v2, and we don't support that in cscore. We should see how difficult that would be, because there are teams that would use it if it were available.

**Comment by sparks58** [comment]
Yes, that is correct. The Jetson comes installed with opencv 2.4. Cscore supports version 3, so you'll need to either install version 3 or compile it yourself. Here is a script that'll compile OpenCV for you: http://www.jetsonhacks.com/2017/04/05/build-opencv-nvidia-jetson-tx2/

**Comment by virtuald** [comment]
I believe the primary issue we have with compiling on a Jetson is that our ndarray <-> mat conversion routines only support OpenCV 3. 

However, you're correct, if someone were to install OpenCV 3.x on a Jetson, this package would work fine.

**Comment by virtuald** [comment]
We're not supporting Python 2 in pynetworktables, and I don't forsee it happening for cscore either unfortunately.
