### ISSUE TITLE
Track cscore/cameraserver in unified allwpilib repo

### ISSUE THREAD

**Issue by auscompgeek** [robotpy/robotpy-cscore#32]
Not sure how we're going to do the cscore part, but it should be easy to track CameraServer.

**Comment by auscompgeek** [comment]
Upstream have added in a function to shutdown cscore, so I think we can stop shipping a patched cscore now too.

**Comment by virtuald** [comment]
I think for cscore it might make sense to use a git subtree approach, since the allwpilib repo is a bit bigger than I would like for a submodule

**Comment by auscompgeek** [comment]
Beta 2 has been tagged, so we should start doing this.

**Comment by auscompgeek** [comment]
Just need to update CameraServer now (and update .gittrack to point to its new home).

**Comment by virtuald** [comment]
Working on CameraServer now.
