### ISSUE TITLE
Compile in CI

### ISSUE THREAD

**Issue by auscompgeek** [robotpy/robotpy-cscore#37]
There appears to be a reasonable Docker image with Python 3 and OpenCV: https://hub.docker.com/r/jjanzic/docker-python3-opencv/

**Comment by virtuald** [comment]
Actually, I wonder if we can just use apt on travis.. they didn't have Xenial available previously, but maybe it would work now?

**Comment by auscompgeek** [comment]
No Ubuntu release has OpenCV with Python 3 bindings, unfortunately.

**Comment by ThadHouse** [comment]
I would recommend using Azure's CI. We've been using it at WPILib and its super awesome. And its docker support is nice as well (we use the docker support for building WPILib).  It's 16.04 base image also has sudo apt support as well.
