### ISSUE TITLE
Add resources generation

### ISSUE THREAD

**Issue by virtuald** [robotpy/robotpy-cscore#42]
New wpiutil generates files that include things like bootstrap et al into C++ files for the webserver to consume.

**Comment by virtuald** [comment]
Python resource generator: https://github.com/wpilibsuite/FRCVision-pi-gen/blob/d1744603840d425e962c34897c448eda03d26f41/deps/tools/gen_resource.py#L1

**Comment by virtuald** [comment]
Sounds like this will be needed in the future, but not currently.

**Comment by auscompgeek** [comment]
I'm guessing if we do #86 we wouldn't have to worry about this.

**Comment by virtuald** [comment]
OBE via #114
