### ISSUE TITLE
error installing cscore bc of numpy

### ISSUE THREAD

**Issue by pchsRoboticPgram** [robotpy/robotpy-cscore#62]
Trying to install robotpy-cscore, but program is not finding numpy even though I have it installed. I am using pycharm. pls help us. Also is there another way besides this method to access the axis camera or USB camera on to the smart dashboard?
![pic](https://user-images.githubusercontent.com/40650058/51578030-1afd1c80-1e60-11e9-9351-e066a35a5ae6.PNG)
![pic2](https://user-images.githubusercontent.com/40650058/51578106-79c29600-1e60-11e9-859e-d3c83324d50b.PNG)
![pic3](https://user-images.githubusercontent.com/40650058/51578886-2e5db700-1e63-11e9-8fad-f274ed6ff217.PNG)

**Comment by ArchdukeTim** [comment]
Looks like it's not installing robotpy-cscore in the same venv as your project

**Comment by pchsRoboticPgram** [comment]
how can this be fixed? how do is it try to install on a different environment? Sorry I'm new to this kind of stuff.

**Comment by ArchdukeTim** [comment]
I think if you run `C:\Desktop\KyleAndDaitensFirstProgram\venv\Scripts\python.exe -m pip install robotpy-cscore` it should work

**Comment by pchsRoboticPgram** [comment]
![pic4](https://user-images.githubusercontent.com/40650058/51583261-d2e7f500-1e73-11e9-99b2-4992a6dcbe6b.PNG)

OK this came up...

**Comment by auscompgeek** [comment]
Note that robotpy-cscore currently does not support installation on Windows due to a couple of issues, see #59.

**Comment by auscompgeek** [comment]
Seems likely that doing `import numpy` in C:\Desktop\KyleAndDaitensFirstProgram\venv\Scripts\python.exe would equally break. If so, your virtualenv is broken.

**Comment by pchsRoboticPgram** [comment]
is there a way to make the axis camera show up on the smart dashboard without using the CameraServer class from robotpy-cscore?

**Comment by auscompgeek** [comment]
It's possible, but not as fun. You would have to add the stream values to NetworkTables yourself. You can take a read of the CameraServer class to figure out how to do that.

Note that you don't need to install robotpy-cscore on your dev machine to use it on the robot. The `wpilib.CameraServer` shim will only launch the cscore code if it's on the robot.

**Comment by pchsRoboticPgram** [comment]
Thank you so much! We installed robotpy-cscore directly to the RoboRIO via command prompt and it worked like a charm!
