### ISSUE TITLE
Easy way to save camera settings(such as exposure, hue etc)

### ISSUE THREAD

**Issue by orendanniel015** [robotpy/robotpy-cscore#64]
Hello everyone!

I have my vision processing running on a coprocessor and every time I do things like reboot the machine or disconnect the camera, settings such as brightness and hue get restarted. So what I want to know is if there is a easy way to save these settings using cscore webUI and for later?

**Comment by auscompgeek** [comment]
A VideoSink, such as a UsbCamera, has setConfigJson and getConfigJson methods. I believe the cscore webpage also exposes a way to get the current config as JSON too.

If you only want to set a few settings, you can also use their corresponding setter methods.
