### ISSUE TITLE
Error building bdist_wheel on OSX

### ISSUE THREAD

**Issue by virtuald** [robotpy/robotpy-cscore#7]
Must be something in pybind11's setup script.

**Comment by joshsizer** [comment]
I was wondering if you might be able to help me install on Mac OSX 10.14.2, or atleast tell me that it's not possible at the moment.

Installed on system:
clang: Apple LLVM version 10.0.0 (clang-1000.10.44.4)
opencv: 4.0.1 and 2.4.13.7_2
python: 3.7
numpy: 1.15.4

I get slightly different errors when I use opencv 4 vs opencv 2. It always fails compiling ndarray_converter.cpp.

Here is the error log with opencv4 and opencv2 respectively: 
[install_fail_opencv4.log](https://github.com/robotpy/robotpy-cscore/files/2752271/install_fail_opencv4.log)
[install_fail_opencv2.log](https://github.com/robotpy/robotpy-cscore/files/2752290/install_fail_opencv2.log)

Any help would be appreciated!

**Comment by auscompgeek** [comment]
OpenCV 4 is not supported: #39. OpenCV 2 only supports Python 2.

robotpy-cscore is only compatible with OpenCV 3.

**Comment by joshsizer** [comment]
Ah, this was a suspicion of mine, but there is no opencv3 package on Homebrew. I am starting to think I'll have to compile from source. Do you have any resource that steps me through that process?

**Comment by joshsizer** [comment]
Thanks for the quick responses. This project is awesome, I'd like to say thank you for all the hard work.

**Comment by auscompgeek** [comment]
FYI it seems the Homebrew folk have come to their senses and have an `opencv@3` package now.

**Comment by auscompgeek** [comment]
Looks like the source package on PyPI actually builds now.
