### ISSUE TITLE
gettting nothing while running cam in process

### ISSUE THREAD

**Issue by oriagranat9** [robotpy/robotpy-cscore#77]
while trying to run a usb cam in a process and grabbing its frames the value of the image is 0 
```
#camera is a usb camera object
multiprocessing.Process(target=self.camera_process, args=(cam,camera_server))

 def camera_process(self, camera,cs):
   cv_sink = cscore.CvSink("test")
   cv_sink.setSource(camera)
   while True:
            _, image = cv_sink.grabFrame(image)
```

**Comment by PeterJohnson** [comment]
No, this won't work.  You're going to have to send the images to the subprocess yourself (e.g. via a pipe).

**Comment by virtuald** [comment]
@oriagranat9 what are you trying to accomplish? If you're trying to run this code on a roborio, see the documentation at https://robotpy.readthedocs.io/en/stable/vision/roborio.html

**Comment by oriagranat9** [comment]
no im trying to run this on my computer in and to process each camera in parallel

**Comment by virtuald** [comment]
If you create your camera objects inside the `camera_process` function, it should work.

**Comment by virtuald** [comment]
Closed due to age.
