### ISSUE TITLE
no image is recieved from sony playstation eye camera

### ISSUE THREAD

**Issue by or-dan123** [robotpy/robotpy-cscore#88]
I have compiled the newest version of the library (which I have heard that it now supports ps eye), however when I do automatic capture for the camera I don't receive any image.

what should I do?

**Comment by virtuald** [comment]
What version does `cscore.__version__` report?

**Comment by virtuald** [comment]
Actually, there were commits that were done after December that I missed. Do a `git pull` followed by `git submodule update`, and try again. Sorry for the inconvenience.

**Comment by or-dan123** [comment]
Never mind I have I reread the documentation and added this
camera.setPixelFormat(cscore.VideoMode.PixelFormat.kYUYV) and all works

Thank you for response!
